# -*- coding: utf-8 -*-
"""Training Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2JSeiL_Rtbj5bj8NtsDTGzCyMIBfAq0

# Import Library
"""

import zipfile
import os

"""# Data Loading"""

from google.colab import files

# Upload file kaggle.json dari komputer lokal ke Colab
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!pip install kaggle

!kaggle datasets download vasukipatel/face-recognition-dataset

zip_path = "face-recognition-dataset.zip"
extract_folder = "face_recognition_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print(f"Dataset berhasil diekstrak ke folder: {extract_folder}")

"""# Data Preprocessing"""

# def generate_ids_for_folders(base_path):
#     folder_list = [f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))]
#     print(f"Ditemukan folder (label nama): {folder_list}")

#     for idx, folder_name in enumerate(sorted(folder_list), start=1):
#         folder_path = os.path.join(base_path, folder_name)
#         id_file_path = os.path.join(folder_path, "id.txt")

#         # Tulis ID unik ke file id.txt di dalam folder
#         with open(id_file_path, "w") as f:
#             f.write(str(idx))

#         print(f"Folder '{folder_name}' diberi ID: {idx}")

# # Jalankan fungsi generate ID
# generate_ids_for_folders(extract_folder)

# import os

# def generate_custom_ids_for_folders(base_path, prefix="MF"):
#     folder_list = [f for f in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, f))]
#     print(f"Ditemukan folder (label nama): {folder_list}")

#     for idx, folder_name in enumerate(sorted(folder_list), start=1):
#         folder_path = os.path.join(base_path, folder_name)
#         id_file_path = os.path.join(folder_path, "id.txt")

#         # Format ID dengan prefix dan angka 5 digit dengan leading zeros
#         unique_id = f"{prefix}{idx:05d}"

#         # Tulis ID unik ke file id.txt di dalam folder
#         with open(id_file_path, "w") as f:
#             f.write(unique_id)

#         print(f"Folder '{folder_name}' diberi ID: {unique_id}")

# # Contoh pemakaian:
# extract_folder = "face_recognition_dataset"  # Ganti dengan path dataset kamu
# generate_custom_ids_for_folders(extract_folder)

import os

def generate_custom_ids_for_nested_folders(base_path, target_subfolder_path, prefix="MF"):
    """
    Generate unique IDs with format PREFIX + 5 digit number (e.g. MF00001)
    for each folder inside the target_subfolder_path nested in base_path,
    and save the ID in id.txt inside each folder.

    Args:
        base_path (str): Root folder path (e.g. "face_recognition_dataset")
        target_subfolder_path (str): Relative path from base_path to target folders (e.g. "Original Images/Original Images")
        prefix (str): Prefix string for the ID. Default is "MF".
    """
    full_target_path = os.path.join(base_path, target_subfolder_path)
    if not os.path.exists(full_target_path):
        print(f"Folder target tidak ditemukan: {full_target_path}")
        return

    folder_list = [f for f in os.listdir(full_target_path) if os.path.isdir(os.path.join(full_target_path, f))]
    print(f"Ditemukan folder (label nama) di '{full_target_path}': {folder_list}")

    for idx, folder_name in enumerate(sorted(folder_list), start=1):
        folder_path = os.path.join(full_target_path, folder_name)
        id_file_path = os.path.join(folder_path, "id.txt")

        # Format ID dengan prefix dan angka 5 digit dengan leading zeros
        unique_id = f"{prefix}{idx:05d}"

        # Tulis ID unik ke file id.txt di dalam folder
        with open(id_file_path, "w") as f:
            f.write(unique_id)

        print(f"Folder '{folder_name}' diberi ID: {unique_id}")

# Contoh pemakaian:
base_folder = "face_recognition_dataset"  # Folder root dataset
target_subfolder = "Original Images/Original Images"  # Folder yang berisi label nama orang

generate_custom_ids_for_nested_folders(base_folder, target_subfolder)

"""# Bagian Image
- resize
-augmentasi
"""

